# Generated by Django 5.1.4 on 2024-12-24 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cation',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 22, 15, 41, 809060)),
        ),
    ]
